services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: todo_frontend
    restart: always
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

