services:
  api:
    build:
      context: .
      target: development
      dockerfile: Dockerfile
      # to be linked later with github vars and secret in ci/cd pipeline
      # args:
      #   PORT: 3000
      #   NODE_ENV: production
      #   POSTGRES_PASSWORD: nestpass
      #   POSTGRES_USER: nestuser
      #   POSTGRES_DB: nestdb
      #   POSTGRES_PORT: 5432
      #   POSTGRES_HOST: postgres=value
    working_dir: /app
    container_name: todo_api
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres
      - adminer
    volumes:
      - .:/app:delegated
      - /app/node_modules
    command: npm run start:dev

  postgres:
    image: postgres
    restart: always
    container_name: todo-dev_db
    ports:
      - 5432:5432
    volumes:
      - todo_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  todo_data:
