version: '3.8'

services:
  api:
    build:
      context: .
      target: production
      dockerfile: Dockerfile
    container_name: todo_api
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    restart: always
    container_name: todo-prod_db
    ports:
      - 5432:5432
    volumes:
      - todo_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  todo_data:
