# ci workflow for fullstack todo app

name: Fullstack Todo | Test CI

on:
  push:
    branches: "*"
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  setup_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

  ci_frontend_test:
    needs: setup_environment
    runs-on: ubuntu-latest
    steps:
    - name: Build Angular project
      run: |
        cd /frontend
        npm run build -- --configuration production
    - name: Run tests on frontend
      run: |
        cd /backend
        npm run 

  ci_backend_test:
    needs: setup_environment
    runs-on: ubuntu-latest
    steps:
      - name: Build Nestjs project
        run: |
          cd /backend
          npm run build
      - name: Run tests on backend
        run: |
          cd /backend
          npm run test